[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000

# Ensure environment variables are available during build
[build.environment]
  NODE_ENV = "production"

# Handle all routes through the Remix server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true 