[build]
  command = "npm run build"
  publish = ".netlify/functions-serve"

[dev]
  command = "npm run dev"
  port = 3000

# Ensure environment variables are available during build
[build.environment]
  NODE_ENV = "production"

# Handle redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 